export default {
  like: 'Likes',
  collects: 'Collects',
  comments: 'Comments',
  productdetails: 'Product Details',
  brand: 'Brand',
  warrenty: 'Warrenty',
  caseSize: 'Case Size',
  caseMaterial: 'Case Material',
  brandMaterial: 'Brand Material',
  whyWatchPro: 'Why Choose Watch Pro',
  shopingReturn: 'Shoping & Returns',
  privacy_policy: 'Privacy Policy',
  youMay: 'You may also like',
  writeComment: 'Write your comment here',
  tax: 'Tax included in price',
  addCart: 'ADD TO CART',
  removeCart: 'REMOVE FROM CART',
  following: 'FOLLOWING',
  follow: 'FOLLOW',
};
