export default {
  like: '喜欢',
  collects: '收集',
  comments: '评论',
  productdetails: '产品详情',
  brand: '品牌',
  warrenty: '保修期',
  caseSize: '外壳尺寸',
  caseMaterial: '案例材料',
  brandMaterial: '品牌材料',
  whyWatchPro: '为什么选择 Watch Pro',
  shopingReturn: '购物和退货',
  privacy_policy: '隐私政策',
  youMay: '你可能也会喜欢',
  writeComment: '在这里写下你的评论',
  tax: '价格已含税',
  addCart: '添加到购物车',
  removeCart: '删除到购物车',
  following: '下列的',
  follow: '跟随',
};
