export enum UserTypes {
  LOGIN = 'LOGIN',
  LOGIN_PENDING = 'LOGIN_PENDING',
  LOGIN_FULFILLED = 'LOGIN_FULFILLED',
  LOGIN_REJECTED = 'LOGIN_REJECTED',

  APPLE_LOGIN = 'APPLE_LOGIN',
  SOCIAL_LOGIN = 'SOCIAL_LOGIN',
  APPLE_LOGIN_PENDING = 'APPLE_LOGIN_PENDING',
  APPLE_LOGIN_FULFILLED = 'APPLE_LOGIN_FULFILLED',
  APPLE_LOGIN_REJECTED = 'APPLE_LOGIN_REJECTED',

  REGISTER = 'REGISTER',
  REGISTER_PENDING = 'REGISTER_PENDING',
  REGISTER_FULFILLED = 'REGISTER_FULFILLED',
  REGISTER_REJECTED = 'REGISTER_REJECTED',

  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  FORGOT_PASSWORD_PENDING = 'FORGOT_PASSWORD_PENDING',
  FORGOT_PASSWORD_FULFILLED = 'FORGOT_PASSWORD_FULFILLED',
  FORGOT_PASSWORD_REJECTED = 'FORGOT_PASSWORD_REJECTED',

  SHOP = 'SHOP',
  SHOP_PENDING = 'SHOP_PENDING',
  SHOP_FULFILLED = 'SHOP_FULFILLED',
  SHOP_REJECTED = 'SHOP_REJECTED',

  RESET_PASSWORD = 'RESER_PASSWORD',
  RESET_PASSWORD_PENDING = 'RESER_PASSWORD_PENDING',
  RESET_PASSWORD_FULFILLED = 'RESER_PASSWORD_FULFILLED',
  RESET_PASSWORD_REJECTED = 'RESER_PASSWORD_REJECTED',

  LOGOUT = 'LOGOUT',
}
